#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------



/// <summary>
/// Status de Pet
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.11")]
public enum lks_pet_statecode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Active = 0,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Inactive = 1,
}

/// <summary>
/// Razão do status de Pet
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.11")]
public enum lks_pet_statuscode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Ativo_a = 1,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Inativo_a = 2,
}

[System.Runtime.Serialization.DataContractAttribute()]
[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("lks_pet")]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.11")]
public partial class lks_Pet : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
{
	
		/// <summary>
		/// Available fields, a the time of codegen, for the lks_pet entity
		/// </summary>
		public partial class Fields
		{
			public const string CreatedBy = "createdby";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string ImportSequenceNumber = "importsequencenumber";
			public const string lks_Breed = "lks_breed";
			public const string lks_BreederName = "lks_breedername";
			public const string lks_DateofAdoption = "lks_dateofadoption";
			public const string lks_DateofBirth = "lks_dateofbirth";
			public const string lks_HasBeenAdopted = "lks_hasbeenadopted";
			public const string lks_Name = "lks_name";
			public const string lks_PetId = "lks_petid";
			public const string Id = "lks_petid";
			public const string lks_PetOwnerLookup = "lks_petownerlookup";
			public const string lks_Shelter = "lks_shelter";
			public const string lks_TempPetOwnerName = "lks_temppetownername";
			public const string lks_Type = "lks_type";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string OverriddenCreatedOn = "overriddencreatedon";
			public const string OwnerId = "ownerid";
			public const string OwningBusinessUnit = "owningbusinessunit";
			public const string OwningTeam = "owningteam";
			public const string OwningUser = "owninguser";
			public const string statecode = "statecode";
			public const string statuscode = "statuscode";
			public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
			public const string UTCConversionTimeZoneCode = "utcconversiontimezonecode";
			public const string VersionNumber = "versionnumber";
			public const string lks_Pet_PetOwnerLookup_lks_PetOwner = "lks_Pet_PetOwnerLookup_lks_PetOwner";
			public const string lks_pet_Shelter_lks_shelter = "lks_pet_Shelter_lks_shelter";
		}
	
	/// <summary>
	/// Default Constructor.
	/// </summary>
	public lks_Pet() : 
			base(EntityLogicalName)
	{
	}
	
	public const string EntityLogicalName = "lks_pet";
	
	public const string EntityLogicalCollectionName = "lks_pets";
	
	public const string EntitySetName = "lks_pets";
	
	public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
	
	public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
	
	private void OnPropertyChanged(string propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void OnPropertyChanging(string propertyName)
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
		}
	}
	
	/// <summary>
	/// Identificador exclusivo do usuário que criou o registro.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
	public Microsoft.Xrm.Sdk.EntityReference CreatedBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
		}
	}
	
	/// <summary>
	/// Data e hora de criação do registro.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
	public System.Nullable<System.DateTime> CreatedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
		}
	}
	
	/// <summary>
	/// Identificador exclusivo do usuário delegado que criou o registro.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
	public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
		}
	}
	
	/// <summary>
	/// Número de sequência da importação que criou este registro.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
	public System.Nullable<int> ImportSequenceNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
		}
		set
		{
			this.OnPropertyChanging("ImportSequenceNumber");
			this.SetAttributeValue("importsequencenumber", value);
			this.OnPropertyChanged("ImportSequenceNumber");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("lks_breed")]
	public string lks_Breed
	{
		get
		{
			return this.GetAttributeValue<string>("lks_breed");
		}
		set
		{
			this.OnPropertyChanging("lks_Breed");
			this.SetAttributeValue("lks_breed", value);
			this.OnPropertyChanged("lks_Breed");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("lks_breedername")]
	public string lks_BreederName
	{
		get
		{
			return this.GetAttributeValue<string>("lks_breedername");
		}
		set
		{
			this.OnPropertyChanging("lks_BreederName");
			this.SetAttributeValue("lks_breedername", value);
			this.OnPropertyChanged("lks_BreederName");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("lks_dateofadoption")]
	public System.Nullable<System.DateTime> lks_DateofAdoption
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("lks_dateofadoption");
		}
		set
		{
			this.OnPropertyChanging("lks_DateofAdoption");
			this.SetAttributeValue("lks_dateofadoption", value);
			this.OnPropertyChanged("lks_DateofAdoption");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("lks_dateofbirth")]
	public System.Nullable<System.DateTime> lks_DateofBirth
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("lks_dateofbirth");
		}
		set
		{
			this.OnPropertyChanging("lks_DateofBirth");
			this.SetAttributeValue("lks_dateofbirth", value);
			this.OnPropertyChanged("lks_DateofBirth");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("lks_hasbeenadopted")]
	public System.Nullable<bool> lks_HasBeenAdopted
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("lks_hasbeenadopted");
		}
		set
		{
			this.OnPropertyChanging("lks_HasBeenAdopted");
			this.SetAttributeValue("lks_hasbeenadopted", value);
			this.OnPropertyChanged("lks_HasBeenAdopted");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("lks_name")]
	public string lks_Name
	{
		get
		{
			return this.GetAttributeValue<string>("lks_name");
		}
		set
		{
			this.OnPropertyChanging("lks_Name");
			this.SetAttributeValue("lks_name", value);
			this.OnPropertyChanged("lks_Name");
		}
	}
	
	/// <summary>
	/// Identificador exclusivo de instâncias de entidade
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("lks_petid")]
	public System.Nullable<System.Guid> lks_PetId
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("lks_petid");
		}
		set
		{
			this.OnPropertyChanging("lks_PetId");
			this.SetAttributeValue("lks_petid", value);
			if (value.HasValue)
			{
				base.Id = value.Value;
			}
			else
			{
				base.Id = System.Guid.Empty;
			}
			this.OnPropertyChanged("lks_PetId");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("lks_petid")]
	public override System.Guid Id
	{
		get
		{
			return base.Id;
		}
		set
		{
			this.lks_PetId = value;
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("lks_petownerlookup")]
	public Microsoft.Xrm.Sdk.EntityReference lks_PetOwnerLookup
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("lks_petownerlookup");
		}
		set
		{
			this.OnPropertyChanging("lks_PetOwnerLookup");
			this.SetAttributeValue("lks_petownerlookup", value);
			this.OnPropertyChanged("lks_PetOwnerLookup");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("lks_shelter")]
	public Microsoft.Xrm.Sdk.EntityReference lks_Shelter
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("lks_shelter");
		}
		set
		{
			this.OnPropertyChanging("lks_Shelter");
			this.SetAttributeValue("lks_shelter", value);
			this.OnPropertyChanged("lks_Shelter");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("lks_temppetownername")]
	public string lks_TempPetOwnerName
	{
		get
		{
			return this.GetAttributeValue<string>("lks_temppetownername");
		}
		set
		{
			this.OnPropertyChanging("lks_TempPetOwnerName");
			this.SetAttributeValue("lks_temppetownername", value);
			this.OnPropertyChanged("lks_TempPetOwnerName");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("lks_type")]
	public string lks_Type
	{
		get
		{
			return this.GetAttributeValue<string>("lks_type");
		}
		set
		{
			this.OnPropertyChanging("lks_Type");
			this.SetAttributeValue("lks_type", value);
			this.OnPropertyChanged("lks_Type");
		}
	}
	
	/// <summary>
	/// Identificador exclusivo do usuário que modificou o registro.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
	public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
		}
	}
	
	/// <summary>
	/// Data e hora de modificação do registro.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
	public System.Nullable<System.DateTime> ModifiedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
		}
	}
	
	/// <summary>
	/// Identificador exclusivo do usuário delegado que modificou o registro.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
	public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
		}
	}
	
	/// <summary>
	/// Data e hora da migração do registro.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
	public System.Nullable<System.DateTime> OverriddenCreatedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
		}
		set
		{
			this.OnPropertyChanging("OverriddenCreatedOn");
			this.SetAttributeValue("overriddencreatedon", value);
			this.OnPropertyChanged("OverriddenCreatedOn");
		}
	}
	
	/// <summary>
	/// ID do Proprietário
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
	public Microsoft.Xrm.Sdk.EntityReference OwnerId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
		}
		set
		{
			this.OnPropertyChanging("OwnerId");
			this.SetAttributeValue("ownerid", value);
			this.OnPropertyChanged("OwnerId");
		}
	}
	
	/// <summary>
	/// Identificador exclusivo da unidade de negócios proprietária do registro
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
	public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
		}
	}
	
	/// <summary>
	/// Identificador exclusivo da equipe proprietária do registro.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
	public Microsoft.Xrm.Sdk.EntityReference OwningTeam
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
		}
	}
	
	/// <summary>
	/// Identificador exclusivo do usuário proprietário do registro.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
	public Microsoft.Xrm.Sdk.EntityReference OwningUser
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
		}
	}
	
	/// <summary>
	/// Status de Pet
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
	public virtual lks_pet_statecode? statecode
	{
		get
		{
			return ((lks_pet_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
		}
		set
		{
			this.OnPropertyChanging("statecode");
			this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("statecode");
		}
	}
	
	/// <summary>
	/// Razão do status de Pet
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
	public virtual lks_pet_statuscode? statuscode
	{
		get
		{
			return ((lks_pet_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
		}
		set
		{
			this.OnPropertyChanging("statuscode");
			this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("statuscode");
		}
	}
	
	/// <summary>
	/// Somente para uso interno.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
	public System.Nullable<int> TimeZoneRuleVersionNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
		}
		set
		{
			this.OnPropertyChanging("TimeZoneRuleVersionNumber");
			this.SetAttributeValue("timezoneruleversionnumber", value);
			this.OnPropertyChanged("TimeZoneRuleVersionNumber");
		}
	}
	
	/// <summary>
	/// Código de fuso horário em uso quando o registro foi criado.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
	public System.Nullable<int> UTCConversionTimeZoneCode
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
		}
		set
		{
			this.OnPropertyChanging("UTCConversionTimeZoneCode");
			this.SetAttributeValue("utcconversiontimezonecode", value);
			this.OnPropertyChanged("UTCConversionTimeZoneCode");
		}
	}
	
	/// <summary>
	/// Número da Versão
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
	public System.Nullable<long> VersionNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
		}
	}
	
	/// <summary>
	/// N:1 lks_Pet_PetOwnerLookup_lks_PetOwner
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("lks_petownerlookup")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lks_Pet_PetOwnerLookup_lks_PetOwner")]
	public lks_PetOwner lks_Pet_PetOwnerLookup_lks_PetOwner
	{
		get
		{
			return this.GetRelatedEntity<lks_PetOwner>("lks_Pet_PetOwnerLookup_lks_PetOwner", null);
		}
		set
		{
			this.OnPropertyChanging("lks_Pet_PetOwnerLookup_lks_PetOwner");
			this.SetRelatedEntity<lks_PetOwner>("lks_Pet_PetOwnerLookup_lks_PetOwner", null, value);
			this.OnPropertyChanged("lks_Pet_PetOwnerLookup_lks_PetOwner");
		}
	}
	
	/// <summary>
	/// N:1 lks_pet_Shelter_lks_shelter
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("lks_shelter")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lks_pet_Shelter_lks_shelter")]
	public lks_Shelter lks_pet_Shelter_lks_shelter
	{
		get
		{
			return this.GetRelatedEntity<lks_Shelter>("lks_pet_Shelter_lks_shelter", null);
		}
		set
		{
			this.OnPropertyChanging("lks_pet_Shelter_lks_shelter");
			this.SetRelatedEntity<lks_Shelter>("lks_pet_Shelter_lks_shelter", null, value);
			this.OnPropertyChanged("lks_pet_Shelter_lks_shelter");
		}
	}
}
#pragma warning restore CS1591
